version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/foodtruckk'
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: npm run dev # Start the server in development mode
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: # Named volume for MongoDB data persistence